import { ArrowRight, CalendarClock, MessageSquareWarning, Sparkles, TrendingUp } from "lucide-react";
import { PageHeader } from "@/components/page-header";
import { FunnelChart, RevenueChart } from "@/components/dashboard-charts";
import { appointments, conversations, deals, metrics } from "@/data/demo";

export default function OverviewPage() { return <>
  <PageHeader eyebrow="VISÃO GERAL" title="Bom dia, Augusto" description="A operação da Vértice está saudável. Há três pontos que merecem atenção hoje." action={<select className="input !w-auto" defaultValue="30"><option value="30">Últimos 30 dias</option><option value="90">Últimos 90 dias</option></select>}/>
  <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3 2xl:grid-cols-6">{metrics.map(metric => <article className="card p-4" key={metric.label}><p className="text-xs font-medium text-[var(--muted)]">{metric.label}</p><p className="mt-2 text-xl font-bold tracking-tight">{metric.value}</p><span className={metric.tone === "good" ? "text-xs font-semibold text-[var(--success)]" : "text-xs font-semibold text-[var(--warning)]"}>{metric.change} vs. período anterior</span></article>)}</section>
  <section className="mt-4 grid gap-4 xl:grid-cols-[1.55fr_1fr]"><article className="card p-5"><div className="mb-5 flex items-center justify-between"><div><h2 className="font-semibold">Receita</h2><p className="text-xs text-[var(--muted)]">Realizada e prevista</p></div><span className="badge"><TrendingUp size={13}/> +12,4%</span></div><RevenueChart/></article><article className="card p-5"><h2 className="font-semibold">Funil de vendas</h2><p className="mb-3 text-xs text-[var(--muted)]">Conversão total de 23,7%</p><FunnelChart/></article></section>
  <section className="mt-4 grid gap-4 xl:grid-cols-3"><article className="card p-5 xl:col-span-2"><div className="mb-4 flex items-center gap-2"><Sparkles size={17} className="text-[var(--violet)]"/><h2 className="font-semibold">Sugestão da Lyriq Intelligence</h2></div><p className="max-w-3xl text-sm leading-6">Existem <strong>47 oportunidades sem resposta há mais de cinco dias</strong>. Uma campanha de recuperação custaria aproximadamente R$ 18 e poderia recuperar até R$ 7.400 em vendas.</p><div className="mt-4 flex flex-wrap gap-2"><button className="btn-primary">Preparar campanha <ArrowRight size={15}/></button><button className="btn-secondary">Ver oportunidades</button></div><p className="mt-3 text-[11px] text-[var(--muted)]">A campanha só será enviada depois da sua aprovação.</p></article><article className="card p-5"><div className="mb-4 flex items-center gap-2"><CalendarClock size={17}/><h2 className="font-semibold">Próximos agendamentos</h2></div><div className="space-y-3">{appointments.slice(0,3).map(item => <div key={item.time} className="flex gap-3 border-b pb-3 last:border-0"><span className="text-sm font-bold text-[var(--primary)]">{item.time}</span><div><p className="text-sm font-medium">{item.title}</p><p className="text-xs text-[var(--muted)]">{item.client} · {item.professional}</p></div></div>)}</div></article></section>
  <section className="mt-4 grid gap-4 xl:grid-cols-2"><article className="card p-5"><div className="mb-4 flex items-center gap-2"><MessageSquareWarning size={17}/><h2 className="font-semibold">Conversas que exigem atenção</h2></div>{conversations.slice(0,3).map(c => <div key={c.name} className="flex items-center gap-3 border-b py-3 last:border-0"><div className="grid h-9 w-9 place-items-center rounded-full bg-[var(--surface-2)] text-xs font-bold">{c.name.split(" ").map(n=>n[0]).join("")}</div><div className="min-w-0 flex-1"><p className="text-sm font-medium">{c.name}</p><p className="truncate text-xs text-[var(--muted)]">{c.preview}</p></div><span className="badge">{c.channel}</span></div>)}</article><article className="card p-5"><h2 className="mb-4 font-semibold">Oportunidades paradas</h2>{deals.filter(d=>d.lastInteraction.includes("dias") || d.probability < 60).map(d => <div key={d.id} className="flex items-center justify-between border-b py-3 last:border-0"><div><p className="text-sm font-medium">{d.title}</p><p className="text-xs text-[var(--muted)]">{d.contact} · {d.lastInteraction}</p></div><span className="text-sm font-bold">R$ {d.value.toLocaleString("pt-BR")}</span></div>)}</article></section>
</>; }
