-- Lyriq Business OS: schema multiempresa inicial
create extension if not exists pgcrypto;
create extension if not exists vector;

create type public.member_role as enum ('owner','admin','manager','sales','support','finance','marketing','analyst','viewer');
create type public.record_status as enum ('active','inactive','archived');

create table public.profiles (id uuid primary key references auth.users(id) on delete cascade, full_name text not null, avatar_url text, is_lyriq_admin boolean not null default false, created_at timestamptz not null default now());
create table public.organizations (id uuid primary key default gen_random_uuid(), name text not null, slug text unique not null, segment text not null, status public.record_status not null default 'active', settings jsonb not null default '{}', created_at timestamptz not null default now());
create table public.organization_members (organization_id uuid not null references public.organizations on delete cascade, profile_id uuid not null references public.profiles on delete cascade, role public.member_role not null, status public.record_status not null default 'active', created_at timestamptz not null default now(), primary key(organization_id,profile_id));
create table public.roles (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations on delete cascade, name text not null, key text not null, unique(organization_id,key));
create table public.permissions (id uuid primary key default gen_random_uuid(), role_id uuid not null references public.roles on delete cascade, module text not null, actions text[] not null default '{}', unique(role_id,module));

create or replace function public.is_org_member(target_org uuid) returns boolean language sql stable security definer set search_path='' as $$ select exists(select 1 from public.organization_members m where m.organization_id=target_org and m.profile_id=auth.uid() and m.status='active') $$;
create or replace function public.is_lyriq_admin() returns boolean language sql stable security definer set search_path='' as $$ select coalesce((select p.is_lyriq_admin from public.profiles p where p.id=auth.uid()),false) $$;

create table public.contacts (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations on delete cascade, full_name text not null, email text, phone text, company_name text, source text, status public.record_status not null default 'active', metadata jsonb not null default '{}', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.contact_tags (organization_id uuid not null references public.organizations on delete cascade, contact_id uuid not null references public.contacts on delete cascade, tag text not null, primary key(contact_id,tag));
create table public.products (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations on delete cascade, name text not null, description text, price_cents integer not null check(price_cents>=0), active boolean not null default true);
create table public.services (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations on delete cascade, name text not null, duration_minutes integer, price_cents integer not null check(price_cents>=0), active boolean not null default true);
create table public.pipelines (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations on delete cascade, name text not null, is_default boolean not null default false);
create table public.pipeline_stages (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations on delete cascade, pipeline_id uuid not null references public.pipelines on delete cascade, name text not null, position integer not null, win_probability integer not null default 0 check(win_probability between 0 and 100));
create table public.deals (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations on delete cascade, pipeline_id uuid not null references public.pipelines, stage_id uuid not null references public.pipeline_stages, contact_id uuid references public.contacts, title text not null, owner_id uuid references public.profiles, value_cents integer not null default 0, probability integer not null default 0 check(probability between 0 and 100), source text, product_id uuid references public.products, service_id uuid references public.services, expected_close date, last_interaction_at timestamptz, next_action text, lost_reason text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.activities (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations on delete cascade, contact_id uuid references public.contacts, deal_id uuid references public.deals, kind text not null, body text, actor_id uuid references public.profiles, occurred_at timestamptz not null default now());
create table public.tasks (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations on delete cascade, title text not null, assignee_id uuid references public.profiles, deal_id uuid references public.deals, due_at timestamptz, completed_at timestamptz, created_at timestamptz not null default now());
create table public.channels (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations on delete cascade, provider text not null, name text not null, status text not null default 'disconnected', external_id text, config jsonb not null default '{}');
create table public.conversations (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations on delete cascade, channel_id uuid not null references public.channels, contact_id uuid references public.contacts, assignee_id uuid references public.profiles, status text not null default 'open', agent_paused boolean not null default false, intent text, sentiment text, ai_summary text, updated_at timestamptz not null default now());
create table public.messages (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations on delete cascade, conversation_id uuid not null references public.conversations on delete cascade, direction text not null, author_type text not null, body text, attachment_url text, provider_message_id text, delivery_status text not null default 'queued', idempotency_key text, created_at timestamptz not null default now(), unique(organization_id,idempotency_key));
create table public.message_templates (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations on delete cascade, name text not null, channel text not null, body text not null, status text not null default 'draft');
create table public.agents (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations on delete cascade, name text not null, role text not null, model text not null, status text not null default 'paused', instructions text, tools jsonb not null default '[]', monthly_limit_cents integer not null default 0, approvals jsonb not null default '[]', created_at timestamptz not null default now());
create table public.agent_tools (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations on delete cascade, agent_id uuid not null references public.agents on delete cascade, tool_key text not null, scopes text[] not null default '{}', enabled boolean not null default false, unique(agent_id,tool_key));
create table public.agent_actions (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations on delete cascade, agent_id uuid not null references public.agents, action text not null, input jsonb, output jsonb, approved_by uuid references public.profiles, status text not null, cost_micros bigint not null default 0, created_at timestamptz not null default now());
create table public.knowledge_sources (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations on delete cascade, name text not null, kind text not null, uri text, version integer not null default 1, status text not null default 'pending', updated_at timestamptz not null default now());
create table public.knowledge_chunks (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations on delete cascade, source_id uuid not null references public.knowledge_sources on delete cascade, content text not null, position integer not null, embedding vector, metadata jsonb not null default '{}');
create table public.appointments (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations on delete cascade, contact_id uuid references public.contacts, service_id uuid references public.services, professional_id uuid references public.profiles, starts_at timestamptz not null, ends_at timestamptz not null, status text not null, notes text);
create table public.transactions (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations on delete cascade, contact_id uuid references public.contacts, deal_id uuid references public.deals, kind text not null, amount_cents integer not null, due_date date, paid_at timestamptz, status text not null, attribution_type text, provider text, external_id text, idempotency_key text, unique(organization_id,idempotency_key));
create table public.expenses (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations on delete cascade, description text not null, category text, amount_cents integer not null, due_date date, paid_at timestamptz, status text not null);
create table public.campaigns (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations on delete cascade, name text not null, channel text not null, status text not null default 'draft', estimated_cost_cents integer not null default 0, potential_revenue_cents integer not null default 0, approved_by uuid references public.profiles, created_at timestamptz not null default now());
create table public.campaign_recipients (organization_id uuid not null references public.organizations on delete cascade, campaign_id uuid not null references public.campaigns on delete cascade, contact_id uuid not null references public.contacts, status text not null default 'pending', response_at timestamptz, converted_at timestamptz, primary key(campaign_id,contact_id));
create table public.automations (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations on delete cascade, name text not null, status text not null default 'draft', trigger jsonb not null, conditions jsonb not null default '[]', actions jsonb not null default '[]', created_at timestamptz not null default now());
create table public.automation_executions (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations on delete cascade, automation_id uuid not null references public.automations, status text not null, duration_ms integer, estimated_cost_cents integer not null default 0, error text, started_at timestamptz not null default now(), finished_at timestamptz);
create table public.integrations (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations on delete cascade, provider text not null, status text not null default 'disconnected', permissions text[] not null default '{}', last_sync_at timestamptz, last_error text, secret_ref text, unique(organization_id,provider));
create table public.plans (id uuid primary key default gen_random_uuid(), key text unique not null, name text not null, monthly_price_cents integer, limits jsonb not null);
create table public.subscriptions (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations on delete cascade, plan_id uuid not null references public.plans, status text not null, provider text, external_id text, current_period_end timestamptz);
create table public.usage_events (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations on delete cascade, kind text not null, quantity numeric not null default 1, cost_micros bigint not null default 0, source_id uuid, occurred_at timestamptz not null default now());
create table public.notifications (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations on delete cascade, profile_id uuid references public.profiles, title text not null, body text, read_at timestamptz, created_at timestamptz not null default now());
create table public.audit_logs (id uuid primary key default gen_random_uuid(), organization_id uuid references public.organizations on delete cascade, actor_id uuid references public.profiles, action text not null, entity_type text, entity_id uuid, ip inet, metadata jsonb not null default '{}', created_at timestamptz not null default now());

create index on public.organization_members(profile_id,organization_id);
do $$ declare t text; begin foreach t in array array['contacts','contact_tags','products','services','pipelines','pipeline_stages','deals','activities','tasks','channels','conversations','messages','message_templates','agents','agent_tools','agent_actions','knowledge_sources','knowledge_chunks','appointments','transactions','expenses','campaigns','campaign_recipients','automations','automation_executions','integrations','subscriptions','usage_events','notifications','audit_logs'] loop execute format('create index if not exists %I on public.%I (organization_id)', t||'_organization_idx', t); execute format('alter table public.%I enable row level security',t); execute format('create policy %I on public.%I for all using (public.is_org_member(organization_id)) with check (public.is_org_member(organization_id))',t||'_tenant_isolation',t); end loop; end $$;
alter table public.organizations enable row level security;
create policy organizations_member_read on public.organizations for select using(public.is_org_member(id) or public.is_lyriq_admin());
alter table public.organization_members enable row level security;
create policy memberships_self_read on public.organization_members for select using(profile_id=auth.uid() or public.is_org_member(organization_id));
alter table public.profiles enable row level security;
create policy profiles_self_read on public.profiles for select using(id=auth.uid() or public.is_lyriq_admin());
